name: Docker Image CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        mkdir image
        docker build . --file DDNS/Dockerimages/Dockerfile --tag namesiloddns:v0.3
        docker save namesiloddns:v0.3 > ./image/namesiloddns-v0.3.tar
    
    - name : Upload
      uses: actions/upload-artifact@master
      with:
        name: namesiloddns
        path: image
