name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        mkdir image
        docker build . --file acme-SSL/Dockerfile --tag acmessl:v0.2
        docker save acmessl:v0.2 > ./image/acmessl.tar
    
    - name : Upload
      uses: actions/upload-artifact@master
      with:
        name: acmessl
        path: image
